/**
 * migrate.js
 * Script de migración para crear colecciones y poblar datos en MongoDB.
 *
 * Uso:
 *   npm install mongodb
 *   node migrate.js
 */

import { MongoClient } from "mongodb";
import 'dotenv/config';

const MONGO_URI = process.env.MONGO_URI;
const DB_NAME = 'f5-dash';

// ─── DATOS ───────────────────────────────────────────────────────────────────

const levels = [
  { id: 1, name: 'initial', description: 'Nivel inicial' },
  { id: 2, name: 'medio', description: 'Nivel medio' },
  { id: 3, name: 'advance', description: 'Nivel avanzado' },
];

const competences = [
  { id: 1, name: 'DEMO: Configurar el entorno de trabajo', description: 'Montar y mantener un entorno de desarrollo completo, incluyendo herramientas, frameworks y sistemas de control de versiones.' },
  { id: 2, name: 'Gestionar equipos técnicos', description: 'Coordinar y motivar equipos técnicos, facilitando la comunicación y estableciendo objetivos claros para el desarrollo.' },
  { id: 3, name: 'Diseñar y gestionar bases de datos', description: 'Diseñar y gestionar bases de datos eficientemente, incluyendo esquemas, optimización de consultas y mantenimiento de datos.' },
  { id: 4, name: 'Implementar tests de calidad', description: 'Implementar pruebas unitarias, de integración y end-to-end para garantizar la calidad y fiabilidad del software.' },
  { id: 5, name: 'Despliegue de aplicaciones', description: 'Desplegar aplicaciones en servidores, entornos cloud, configurando servicios y asegurando la escalabilidad y disponibilidad.' },
  { id: 6, name: 'Back-end de aplicaciones', description: 'Desarrollar la lógica del back-end, implementando APIs RESTful y gestionando la autenticación y seguridad.' },
  { id: 7, name: 'Desarrollo de interfaces dinámicas', description: 'Desarrollar interfaces dinámicas y responsivas, implementando interacciones fluidas y optimizando la experiencia de usuario.' },
  { id: 8, name: 'Fundamentos, paradigmas, patrones y calidad del código', description: 'Comprende y aplica los fundamentos de la programación y, sobre esa base, utiliza paradigmas, patrones de diseño y arquitectura, y principios de Clean Code.' },
  { id: 9, name: 'Diseñar interfaces de usuario', description: 'Diseñar interfaces intuitivas aplicando principios de UX/UI, creando prototipos y asegurando la accesibilidad.' },
  { id: 10, name: 'Maquetar interfaces estáticas', description: 'Maquetar interfaces usando HTML y CSS, implementando diseños responsivos y asegurando compatibilidad cross-browser.' },
  { id: 12, name: 'Implementar sistemas de extracción de datos desde la web', description: 'Implementar sistemas de webscrapping con BeautifulSoup o Selenium, respetando políticas y asegurando calidad de datos.' },
  { id: 13, name: 'Evaluar conjuntos de datos', description: 'Evaluar datos utilizando herramientas de análisis y visualización, realizando limpieza y análisis exploratorio.' },
  { id: 14, name: 'Aplicar algoritmos de aprendizaje automático', description: 'Aplicar algoritmos de IA según el problema, seleccionando modelos y evaluando su rendimiento.' },
  { id: 15, name: 'Optimizar parámetros de IA', description: 'Optimizar modelos de IA mediante ajustes finos, validación cruzada y optimización de hiperparámetros.' },
  { id: 16, name: 'IA con Procesamiento de Lenguaje Natural', description: 'Implementar modelos de PLN para análisis de sentimientos, clasificación de texto y generación de lenguaje.' },
  { id: 17, name: 'IA con Computer Vision', description: 'Desarrollar modelos de visión artificial para detección de objetos, reconocimiento facial y análisis de imágenes.' },
  { id: 18, name: 'Desarrollo web de entornos virtuales en 3D', description: 'Diseñar y desarrollar aplicaciones web interactivas en entornos tridimensionales' },
  { id: 19, name: 'Desarrollo web de entornos de realidad virtual (Oculus)', description: 'Crear experiencias inmersivas de realidad virtual accesibles desde navegadores web y dispositivos como Oculus' },
  { id: 20, name: 'Desarrollo web de entornos de realidad aumentada (móvil)', description: 'Desarrollar aplicaciones web que integran elementos virtuales en el entorno físico a través de dispositivos móviles' },
];

const indicators = [
  { id: 1, name: 'Organiza directorios de proyecto', description: 'Crea y mantiene una estructura básica de carpetas para un proyecto.', levelId: 1 },
  { id: 2, name: 'Busca información técnica', description: 'Utiliza herramientas para resolver dudas comunes.', levelId: 1 },
  { id: 3, name: 'Consulta documentación en inglés', description: 'Lee y entiende documentación técnica básica en inglés.', levelId: 1 },
  { id: 4, name: 'Instala aplicaciones y extensiones', description: 'Configura el entorno agregando aplicaciones y extensiones.', levelId: 1 },
  { id: 5, name: 'Usa líneas de comandos básicas', description: 'Navega directorios y ejecuta comandos simples en terminal.', levelId: 2 },
  { id: 6, name: 'Declara funciones y variables en el entorno', description: 'Utiliza funciones, variables y configuraciones en archivos de entorno.', levelId: 2 },
  { id: 7, name: 'Integra control de versiones', description: 'Inicializa y gestiona un repositorio con Git, incluyendo commits y branches.', levelId: 2 },
  { id: 8, name: 'Establece un flujo de trabajo profesional', description: 'Define y aplica un flow de trabajo con ramas, revisiones y despliegue.', levelId: 3 },
  { id: 9, name: 'Utiliza herramientas de contenización', description: 'Configura entornos reproducibles con Docker u otras soluciones.', levelId: 3 },
  { id: 10, name: 'Automatiza el entorno con scripts', description: 'Crea scripts para automatizar tareas de configuración del entorno.', levelId: 3 },
  { id: 11, name: 'Conoce principios ágiles', description: 'Identifica los principios de metodologías ágiles como Scrum o Kanban.', levelId: 1 },
  { id: 12, name: 'Participa en ceremonias Scrum', description: 'Asiste activamente a reuniones como Daily, Sprint Planning y Retrospectiva.', levelId: 1 },
  { id: 13, name: 'Utiliza herramientas de equipo', description: 'Usa herramientas como Trello, Jira o GitHub Projects para seguir tareas del equipo.', levelId: 1 },
  { id: 14, name: 'Facilita reuniones Scrum', description: 'Puede moderar dailies, retros o sprint plannings en un equipo ágil.', levelId: 2 },
  { id: 15, name: 'Fomenta la colaboración entre roles', description: 'Promueve la comunicación efectiva entre devs, QA, y otros perfiles.', levelId: 2 },
  { id: 16, name: 'Aplica mejoras al proceso', description: 'Sugiere y aplica mejoras al flujo de trabajo del equipo.', levelId: 2 },
  { id: 17, name: 'Define procesos ágiles adaptados', description: 'Diseña o adapta marcos ágiles según el contexto del equipo/proyecto.', levelId: 3 },
  { id: 18, name: 'Mentoriza a miembros del equipo', description: 'Apoya el crecimiento profesional de otros a través de mentoring o coaching.', levelId: 3 },
  { id: 19, name: 'Gestión de conflictos y feedback', description: 'Resuelve conflictos y facilita conversaciones difíciles dentro del equipo.', levelId: 3 },
  { id: 20, name: 'Modela datos y relaciones según los requisitos del sistema', description: 'Identifica entidades, atributos y relaciones para estructurar la información de manera lógica y comprensible.', levelId: 1 },
  { id: 21, name: 'Organiza datos en modelos estructurados y semiestructurados', description: 'Diferencia y aplica modelos de datos como tabulares, documentales, grafos o clave-valor según el contexto.', levelId: 1 },
  { id: 22, name: 'Garantiza la integridad y la calidad de los datos', description: 'Aplica principios para evitar errores, duplicidades y asegurar la consistencia de la información.', levelId: 1 },
  { id: 23, name: 'Integra modelos de datos con aplicaciones y servicios', description: 'Conecta la base de datos con sistemas de lógica de negocio, APIs o interfaces de usuario.', levelId: 2 },
  { id: 24, name: 'Selecciona y justifica el modelo de datos más adecuado', description: 'Evalúa cuándo utilizar modelos relacionales, documentales, de grafos, etc., según los requisitos funcionales y no funcionales.', levelId: 2 },
  { id: 25, name: 'Aplica estrategias de organización y optimización de datos', description: 'Utiliza técnicas como normalización, desnormalización, particionamiento o agregación para mejorar la eficiencia y la escalabilidad.', levelId: 2 },
  { id: 26, name: 'Diseña estructuras de datos complejas y escalables', description: 'Crea modelos que soportan relaciones jerárquicas, múltiples asociaciones, o grandes volúmenes de información.', levelId: 3 },
  { id: 27, name: 'Realiza operaciones básicas de consulta y manipulación de datos', description: 'Extrae, filtra y modifica información de acuerdo a necesidades simples del sistema.', levelId: 1 },
  { id: 28, name: 'Realiza operaciones de consulta y manipulación intermedias', description: 'Gestiona búsquedas, filtrados, ordenamientos y agrupaciones de datos complejos.', levelId: 2 },
  { id: 29, name: 'Optimiza el rendimiento de acceso y manipulación de datos', description: 'Implementa estrategias para mejorar la velocidad, concurrencia y escalabilidad de las operaciones sobre los datos.', levelId: 3 },
  { id: 30, name: 'Gestiona la seguridad, disponibilidad y recuperación de la información', description: 'Aplica mecanismos de control de acceso, respaldo, replicación y recuperación ante fallos.', levelId: 3 },
  { id: 31, name: 'Ejecuta pruebas manuales sobre interfaces o flujos simples', description: 'Realiza validaciones manuales para verificar que el software cumple con los requisitos básicos.', levelId: 1 },
  { id: 32, name: 'Implementa pruebas de integración entre módulos', description: 'Desarrolla pruebas que validan la interacción entre distintas partes del sistema.', levelId: 2 },
  { id: 33, name: 'Aplica técnicas como TDD o BDD', description: 'Diseña el desarrollo del software a partir de pruebas automatizadas basadas en comportamiento o requisitos.', levelId: 2 },
  { id: 34, name: 'Utiliza técnicas de simulación de dependencias', description: 'Aplica técnicas de aislamiento como mocking o stubbing para probar componentes de forma independiente.', levelId: 2 },
  { id: 35, name: 'Establece un umbral de cobertura de pruebas', description: 'Define objetivos de cobertura de código y asegura su cumplimiento mediante herramientas de análisis.', levelId: 3 },
  { id: 36, name: 'Diseña pruebas de compatibilidad en múltiples entornos', description: 'Implementa estrategias para validar el comportamiento del software en distintos navegadores, dispositivos o versiones.', levelId: 3 },
  { id: 37, name: 'Automatiza pruebas en pipelines de desarrollo', description: 'Integra pruebas automatizadas en el flujo de integración y entrega continua.', levelId: 3 },
  { id: 38, name: 'Empaqueta una aplicación para su despliegue', description: 'Organiza el código y los recursos necesarios para que la aplicación pueda ser ejecutada en distintos entornos.', levelId: 1 },
  { id: 39, name: 'Utiliza contenedores para ejecutar aplicaciones', description: 'Ejecuta una aplicación en un entorno aislado, replicable y portátil.', levelId: 1 },
  { id: 40, name: 'Publica aplicaciones en entornos gestionados', description: 'Realiza despliegues básicos en plataformas accesibles desde la nube.', levelId: 1 },
  { id: 41, name: 'Define configuraciones para distintos entornos', description: 'Gestiona variables, secretos y configuraciones para despliegue en entornos de desarrollo, pruebas y producción.', levelId: 2 },
  { id: 42, name: 'Automatiza despliegues con flujos de integración', description: 'Implementa procesos que integran, prueban y despliegan automáticamente los cambios en la aplicación.', levelId: 2 },
  { id: 43, name: 'Gestiona redes y volúmenes en contenedores', description: 'Configura conectividad entre servicios y almacenamiento persistente dentro del entorno de ejecución.', levelId: 2 },
  { id: 44, name: 'Orquesta múltiples servicios en contenedores', description: 'Define y gestiona entornos con múltiples servicios coordinados y escalables.', levelId: 3 },
  { id: 45, name: 'Implementa pipelines de entrega continua', description: 'Diseña procesos automatizados que validan, prueban y despliegan el software de forma continua.', levelId: 3 },
  { id: 46, name: 'Evalúa servicios cloud para despliegue', description: 'Selecciona e integra soluciones en la nube que optimicen rendimiento, escalabilidad y costos.', levelId: 3 },
  { id: 48, name: 'Interpreta las necesidades del back-end', description: 'Analiza una interfaz de usuario para identificar qué funciones debe cubrir el servidor.', levelId: 1 },
  { id: 49, name: 'Evalúa funcionalidades comunes en el back-end', description: 'Relaciona necesidades funcionales con conceptos como rutas, controladores o servicios.', levelId: 1 },
  { id: 50, name: 'Describe las responsabilidades del servidor', description: 'Distingue claramente qué parte del sistema se ejecuta del lado del cliente y cuál del lado del servidor.', levelId: 1 },
  { id: 51, name: 'Diseña la estructura del back-end', description: 'Define cómo se organizarán rutas, controladores, modelos y servicios.', levelId: 1 },
  { id: 52, name: 'Elige patrones de arquitectura apropiados', description: 'Selecciona patrones como MVC, servicios distribuidos u otros según los requisitos del sistema.', levelId: 2 },
  { id: 53, name: 'Documenta la arquitectura del sistema', description: 'Crea diagramas y descripciones técnicas de la estructura general del back-end.', levelId: 2 },
  { id: 54, name: 'Implementa funciones del lado del servidor', description: 'Desarrolla lógica que procesa peticiones, datos y respuestas para satisfacer las necesidades de la aplicación.', levelId: 2 },
  { id: 55, name: 'Gestiona la estructura de datos y persistencia', description: 'Define y manipula estructuras de datos para almacenar, consultar y modificar información.', levelId: 2 },
  { id: 56, name: 'Gestiona rutas, controladores y servicios', description: 'Desarrolla componentes que separan responsabilidades dentro del back-end.', levelId: 3 },
  { id: 57, name: 'Desarrolla interacciones dinámicas en tiempo real', description: 'Implementa funciones que permiten actualizaciones en tiempo real entre el cliente y el servidor.', levelId: 3 },
  { id: 58, name: 'Implementa manejo de logs y monitoreo del back-end', description: 'Registra y analiza eventos del sistema para asegurar trazabilidad y diagnóstico.', levelId: 3 },
  { id: 59, name: 'Aplica principios básicos de diseño visual', description: 'Organiza elementos de interfaz respetando jerarquía, alineación, contraste y espaciado.', levelId: 1 },
  { id: 60, name: 'Sigue especificaciones visuales', description: 'Adapta el diseño respetando la carta gráfica o sistema visual definido.', levelId: 1 },
  { id: 61, name: 'Representa interfaces en prototipos de baja fidelidad', description: 'Dibuja pantallas y flujos básicos que permiten visualizar una idea inicial.', levelId: 1 },
  { id: 62, name: 'Diseña interfaces adaptables a múltiples dispositivos', description: 'Crea composiciones visuales que mantienen consistencia y legibilidad en distintos formatos.', levelId: 2 },
  { id: 63, name: 'Incorpora principios de accesibilidad en el diseño', description: 'Toma decisiones visuales y estructurales que favorecen la inclusión.', levelId: 2 },
  { id: 64, name: 'Define flujos de usuario claros', description: 'Establece rutas e interacciones necesarias para que el usuario complete tareas con eficiencia.', levelId: 2 },
  { id: 65, name: 'Aplica fundamentos de UX/UI en interfaces', description: 'Integra usabilidad, estética y coherencia en la experiencia visual del sistema.', levelId: 2 },
  { id: 66, name: 'Construye prototipos interactivos de alta fidelidad', description: 'Simula interacciones entre pantallas permitiendo validar flujos completos.', levelId: 3 },
  { id: 67, name: 'Conduce pruebas de usabilidad con usuarios reales', description: 'Evalúa cómo interactúan las personas con una interfaz para detectar barreras o fricciones.', levelId: 3 },
  { id: 68, name: 'Itera los diseños según resultados de validación', description: 'Refina propuestas visuales con base en observaciones y retroalimentación.', levelId: 3 },
  { id: 69, name: 'Interpreta las necesidades de una interfaz dinámica', description: 'Identifica los requerimientos funcionales y visuales para desarrollar o actualizar una interfaz de usuario.', levelId: 1 },
  { id: 70, name: 'Selecciona herramientas adecuadas para el desarrollo de interfaces', description: 'Evalúa y elige entornos o librerías básicas según las necesidades de la interfaz.', levelId: 1 },
  { id: 71, name: 'Crea o modifica páginas con elementos visuales interactivos básicos', description: 'Desarrolla pantallas que incluyen botones, formularios u otros elementos dinámicos simples.', levelId: 1 },
  { id: 72, name: 'Desarrolla funciones que responden a la interacción del usuario', description: 'Implementa comportamiento dinámico como validaciones, animaciones o cambios de estado en la interfaz.', levelId: 2 },
  { id: 73, name: 'Adapta interfaces a distintos dispositivos y entornos', description: 'Ajusta el diseño y funcionalidad para garantizar usabilidad en distintos tamaños y condiciones.', levelId: 2 },
  { id: 74, name: 'Integra servicios externos o librerías en la interfaz', description: 'Utiliza recursos externos para enriquecer la experiencia de usuario.', levelId: 2 },
  { id: 75, name: 'Aplica criterios de accesibilidad, seguridad y ecodiseño', description: 'Implementa soluciones que reducen impacto ambiental, mejoran el acceso universal y protegen los datos.', levelId: 2 },
  { id: 76, name: 'Desarrolla componentes reutilizables para interfaces complejas', description: 'Crea unidades modulares y adaptativas para gestionar partes de la interfaz que se reutilizan.', levelId: 3 },
  { id: 78, name: 'Participa en el monitoreo y mejora continua de herramientas de interfaz', description: 'Explora nuevas herramientas y tendencias aplicables al desarrollo de interfaces.', levelId: 3 },
  { id: 79, name: 'Aplica principios de diseño modular y basado en componentes', description: 'Organiza la interfaz siguiendo enfoques como Atomic Design, promoviendo la reutilización, consistencia y escalabilidad.', levelId: 3 },
  { id: 80, name: 'Desarrolla pruebas de integración para verificar la interacción entre componentes', description: 'Asegura que los componentes funcionen correctamente en conjunto.', levelId: 2 },
  { id: 81, name: 'Organiza el código con funciones claras y reutilizables', description: 'Aplica lógica estructurada y define funciones para evitar repeticiones innecesarias.', levelId: 1 },
  { id: 82, name: 'Utiliza nombres descriptivos y estructuras limpias', description: 'Asigna nombres claros a variables, funciones y archivos, y mantiene una estructura de código legible.', levelId: 1 },
  { id: 83, name: 'Aplica principios básicos como DRY y KISS', description: 'Evita duplicación de código y mantiene las soluciones lo más simples posible.', levelId: 1 },
  { id: 84, name: 'Aplica los principios de SOLID', description: 'Implementa código que respeta separación de responsabilidades, modularidad y flexibilidad.', levelId: 2 },
  { id: 85, name: 'Utiliza patrones de arquitectura en la organización del sistema', description: 'Organiza componentes del software en estructuras como MVC o arquitectura hexagonal.', levelId: 2 },
  { id: 86, name: 'Reconoce y aplica patrones de diseño', description: 'Implementa soluciones reutilizables organizadas por tipo: creacionales, estructurales o de comportamiento.', levelId: 2 },
  { id: 87, name: 'Adapta el estilo de codificación a paradigmas de programación', description: 'Aplica diferentes enfoques como orientado a objetos, funcional o declarativo según el caso.', levelId: 3 },
  { id: 88, name: 'Diseña sistemas sostenibles a largo plazo', description: 'Toma decisiones estructurales considerando mantenibilidad, escalabilidad y claridad.', levelId: 3 },
  { id: 90, name: 'Maqueta páginas utilizando estructuras semánticas básicas', description: 'Construye el esqueleto de una página siguiendo buenas prácticas de organización y semántica.', levelId: 1 },
  { id: 91, name: 'Aplica estilos básicos de forma coherente', description: 'Estiliza contenido utilizando hojas de estilo ordenadas y con convenciones claras.', levelId: 1 },
  { id: 92, name: 'Adapta la interfaz para que se visualice correctamente en distintos dispositivos', description: 'Aplica principios de diseño responsivo para asegurar la visualización en múltiples formatos.', levelId: 1 },
  { id: 93, name: 'Aplica normativas de accesibilidad en la maquetación', description: 'Integra atributos, estructura y contrastes adecuados para que el contenido sea accesible.', levelId: 2 },
  { id: 94, name: 'Actualiza o mejora estructuras estáticas existentes', description: 'Realiza mejoras en el código HTML/CSS de interfaces existentes sin alterar su funcionalidad.', levelId: 2 },
  { id: 95, name: 'Adapta estructuras según requisitos multilingües y legales', description: 'Considera internacionalización, traducciones y avisos legales durante la maquetación.', levelId: 2 },
  { id: 97, name: 'Valida la accesibilidad y compatibilidad de la interfaz', description: 'Verifica que la interfaz cumpla con criterios técnicos de accesibilidad y soporte en distintos navegadores y dispositivos.', levelId: 3 },
  { id: 98, name: 'Integra principios de ecodiseño y seguridad en la maquetación', description: 'Optimiza el rendimiento y aplica medidas de seguridad desde el diseño estático.', levelId: 3 },
  { id: 99, name: 'Aplica procedimientos de prueba y aceptación de interfaces', description: 'Colabora en la validación de calidad visual, estructural y funcional antes del despliegue.', levelId: 3 },
  { id: 101, name: 'Aplica técnicas de encriptación y tokenización en el back-end', description: 'Protege datos sensibles mediante mecanismos como encriptación simétrica/asimétrica, hash y tokens de acceso.', levelId: 3 },
  { id: 102, name: 'Comprende la estructura de páginas web y el modelo DOM', description: 'Identifica cómo se organizan los elementos en un documento HTML para localizar y extraer información.', levelId: 1 },
  { id: 103, name: 'Utiliza herramientas para simular interacciones web', description: 'Configura entornos que permiten simular acciones de usuario como clics o scrolls para acceder a datos dinámicos.', levelId: 1 },
  { id: 104, name: 'Desarrolla tareas de scraping estructuradas y repetibles', description: 'Implementa scripts que extraen datos de forma ordenada y reproducible desde páginas web o APIs.', levelId: 2 },
  { id: 105, name: 'Integra sistemas de extracción con tareas automatizadas', description: 'Utiliza cron o planificadores para ejecutar tareas de scraping en intervalos definidos.', levelId: 2 },
  { id: 106, name: 'Aplica principios legales y éticos en la extracción de datos', description: 'Identifica los límites legales de scraping y actúa respetando términos de uso y privacidad.', levelId: 3 },
  { id: 107, name: 'Evalúa la calidad y completitud de los datos extraídos', description: 'Implementa mecanismos de control para validar los datos recogidos antes de usarlos.', levelId: 3 },
  { id: 120, name: 'Identifica los parámetros clave en un modelo de IA', description: 'Reconoce los elementos ajustables que afectan el comportamiento del modelo.', levelId: 1 },
  { id: 121, name: 'Aplica métricas básicas para evaluar modelos', description: 'Utiliza medidas estándar como precisión o error para entender el rendimiento del modelo.', levelId: 1 },
  { id: 122, name: 'Distingue entre sobreajuste y subajuste', description: 'Comprende los conceptos de generalización y errores asociados al entrenamiento.', levelId: 1 },
  { id: 123, name: 'Ajusta hiperparámetros para mejorar el rendimiento', description: 'Modifica valores como tasa de aprendizaje o número de capas para optimizar resultados.', levelId: 2 },
  { id: 124, name: 'Implementa validación cruzada para evaluar estabilidad', description: 'Evalúa modelos en diferentes subconjuntos para obtener medidas confiables.', levelId: 2 },
  { id: 125, name: 'Aplica técnicas para equilibrar conjuntos desbalanceados', description: 'Emplea métodos como sobremuestreo o ponderación para mejorar la equidad del modelo.', levelId: 2 },
  { id: 126, name: 'Combina múltiples modelos para mejorar predicciones', description: 'Desarrolla soluciones con técnicas de ensemble para aumentar precisión y robustez.', levelId: 3 },
  { id: 127, name: 'Optimiza el flujo de entrenamiento en modelos complejos', description: 'Configura flujos que incluyen carga, preprocesamiento y ajuste automático de parámetros.', levelId: 3 },
  { id: 128, name: 'Aplica principios éticos y de interpretabilidad', description: 'Analiza el impacto, transparencia y sesgos del modelo durante su optimización.', levelId: 3 },
  { id: 129, name: 'Preprocesa texto para análisis automático', description: 'Aplica técnicas básicas como limpieza, tokenización, lematización y eliminación de ruido.', levelId: 1 },
  { id: 130, name: 'Reconoce tareas comunes en PLN', description: 'Distingue entre análisis de sentimientos, clasificación de texto, extracción de entidades, etc.', levelId: 1 },
  { id: 131, name: 'Representa texto numéricamente', description: 'Utiliza métodos como Bag of Words, TF-IDF, para vectorizar texto.', levelId: 1 },
  { id: 132, name: 'Implementa modelos de clasificación de texto', description: 'Implementa soluciones que asignan categorías a fragmentos de texto usando algoritmos de machine learning clásicos.', levelId: 2 },
  { id: 133, name: 'Integra texto preprocesado en un flujo de modelado', description: 'Conecta transformaciones de texto con modelos de aprendizaje automático.', levelId: 2 },
  { id: 134, name: 'Evalúa la calidad de modelos aplicados a lenguaje', description: 'Analiza coherencia, cobertura y precisión de las salidas textuales.', levelId: 2 },
  { id: 135, name: 'Integra y utiliza APIs de modelos de lenguaje (LLMs)', description: 'Desarrolla aplicaciones que generan o resumen texto utilizando APIs de modelos de lenguaje preentrenados.', levelId: 2 },
  { id: 138, name: 'Transforma imágenes para su análisis', description: 'Aplica operaciones como escalado, recorte y normalización.', levelId: 1 },
  { id: 139, name: 'Diferencia tareas comunes en visión artificial', description: 'Identifica clasificación, detección de objetos, segmentación, etc.', levelId: 1 },
  { id: 141, name: 'Desarrolla modelos para clasificación visual', description: 'Crea sistemas capaces de reconocer categorías en imágenes.', levelId: 2 },
  { id: 142, name: 'Aplica aumento de datos en imágenes', description: 'Utiliza transformaciones visuales para generar nuevas muestras de entrenamiento.', levelId: 2 },
  { id: 144, name: 'Implementa modelos para detectar y localizar objetos', description: 'Desarrolla soluciones que identifican múltiples elementos en una imagen con un bounding box.', levelId: 3 },
  { id: 145, name: 'Evalúa modelos visuales con métricas específicas', description: 'Utiliza medidas como mAP o IoU para evaluar la precisión de detección.', levelId: 3 },
  { id: 146, name: 'Aplica visión artificial en contextos complejos o en tiempo real', description: 'Integra procesamiento de imágenes en flujos dinámicos con múltiples condiciones.', levelId: 3 },
  { id: 147, name: 'Ejecuta contenedor', description: 'Define y ejecuta contenedores con configuraciones básicas.', levelId: 1 },
  { id: 148, name: 'Construye imagen', description: 'Crea imágenes a partir de archivos declarativos.', levelId: 1 },
  { id: 149, name: 'Controla contenedor', description: 'Inicia, detiene y elimina contenedores según necesidad.', levelId: 1 },
  { id: 150, name: 'Orquesta servicios', description: 'Define múltiples servicios con archivos de composición.', levelId: 2 },
  { id: 151, name: 'Gestiona volúmenes', description: 'Configura almacenamiento persistente para contenedores.', levelId: 2 },
  { id: 152, name: 'Configura red', description: 'Establece redes virtuales entre contenedores.', levelId: 2 },
  { id: 153, name: 'Optimiza imagen', description: 'Reduce tamaño y tiempos de construcción de imágenes.', levelId: 3 },
  { id: 154, name: 'Aplica seguridad', description: 'Limita permisos y expone mínimamente los contenedores.', levelId: 3 },
  { id: 155, name: 'Integra en CI/CD', description: 'Usa contenedores en flujos de integración y despliegue.', levelId: 3 },
  { id: 156, name: 'Estructura HTML', description: 'Define la estructura básica de una página web.', levelId: 1 },
  { id: 157, name: 'Etiquetas comunes', description: 'Usa elementos como títulos, párrafos, listas y enlaces.', levelId: 1 },
  { id: 158, name: 'Inserta multimedia', description: 'Agrega imágenes, audio o video en una página.', levelId: 1 },
  { id: 159, name: 'Usa semántica', description: 'Aplica etiquetas semánticas para mejorar estructura y accesibilidad.', levelId: 2 },
  { id: 160, name: 'Formularios', description: 'Crea formularios con campos, botones y validación básica.', levelId: 2 },
  { id: 161, name: 'Organiza contenido', description: 'Usa secciones, artículos y navegación correctamente.', levelId: 2 },
  { id: 162, name: 'Accesibilidad web', description: 'Aplica atributos y roles para accesibilidad (a11y).', levelId: 3 },
  { id: 163, name: 'Optimiza estructura', description: 'Mejora el orden del HTML para rendimiento y mantenimiento.', levelId: 3 },
  { id: 164, name: 'Integra con CSS/JS', description: 'Estructura el HTML para facilitar estilos y comportamiento.', levelId: 3 },
  { id: 165, name: 'Estilos básicos', description: 'Aplica color, tipografía, márgenes y rellenos.', levelId: 1 },
  { id: 166, name: 'Selectores', description: 'Usa selectores simples y combinados para aplicar estilos.', levelId: 1 },
  { id: 167, name: 'Clases y IDs', description: 'Asocia estilos mediante clases e identificadores.', levelId: 1 },
  { id: 168, name: 'Diseño responsivo', description: 'Adapta el diseño a distintos dispositivos con media queries.', levelId: 2 },
  { id: 169, name: 'Modelo de caja', description: 'Comprende y aplica bordes, márgenes y tamaños correctamente.', levelId: 2 },
  { id: 170, name: 'Layouts flexibles', description: 'Crea estructuras usando Flexbox o Grid.', levelId: 2 },
  { id: 171, name: 'Organiza estilos', description: 'Estructura el CSS de forma mantenible y reutilizable.', levelId: 3 },
  { id: 172, name: 'Accesibilidad visual', description: 'Asegura contraste, visibilidad y foco adecuado.', levelId: 3 },
  { id: 173, name: 'Optimiza estilos', description: 'Reduce redundancia y mejora el rendimiento visual.', levelId: 3 },
  { id: 174, name: 'Init y commit', description: 'Inicializa repos y registra cambios con commits simples.', levelId: 1 },
  { id: 175, name: 'Status y log', description: 'Consulta el estado del repositorio y el historial de cambios.', levelId: 1 },
  { id: 176, name: 'Ramas básicas', description: 'Crea y cambia entre ramas de trabajo locales.', levelId: 1 },
  { id: 177, name: 'Clone y pull', description: 'Clona repos y sincroniza con cambios remotos.', levelId: 2 },
  { id: 178, name: 'Push y merge', description: 'Envía cambios y combina ramas de forma controlada.', levelId: 2 },
  { id: 179, name: 'Resuelve conflictos', description: 'Identifica y soluciona conflictos de fusión entre ramas.', levelId: 2 },
  { id: 180, name: 'Flujo Git', description: 'Sigue convenciones como Git Flow o trunk-based development.', levelId: 3 },
  { id: 181, name: 'Commits claros', description: 'Escribe mensajes descriptivos y estructurados para los commits.', levelId: 3 },
  { id: 182, name: 'Hooks y CI', description: 'Integra Git con procesos de validación o despliegue automático.', levelId: 3 },
  { id: 183, name: 'Repo remoto', description: 'Crea y gestiona repos en la plataforma.', levelId: 1 },
  { id: 184, name: 'Push a GitHub', description: 'Sube commits locales a repositorios remotos.', levelId: 1 },
  { id: 185, name: 'Explora cambios', description: 'Consulta commits, ramas y archivos desde la interfaz web.', levelId: 1 },
  { id: 186, name: 'Pull request', description: 'Crea y gestiona solicitudes de cambio entre ramas.', levelId: 2 },
  { id: 187, name: 'Code review', description: 'Participa en revisiones de código con comentarios y sugerencias.', levelId: 2 },
  { id: 188, name: 'Gestiona ramas', description: 'Protege, elimina o sincroniza ramas desde el repo remoto.', levelId: 2 },
  { id: 189, name: 'GitHub Actions', description: 'Configura flujos automáticos de CI/CD en el repositorio.', levelId: 3 },
  { id: 190, name: 'Gestión de issues', description: 'Crea, etiqueta y organiza incidencias del proyecto.', levelId: 3 },
  { id: 191, name: 'Boards y milestones', description: 'Planifica tareas y controla avances con herramientas de proyecto.', levelId: 3 },
  { id: 192, name: 'Crea una escena 3D básica', description: 'Usa primitivas, fondo y luz para construir un entorno simple.', levelId: 1 },
  { id: 193, name: 'Modifica propiedades básicas', description: 'Cambia color, tamaño y posición de los objetos en la escena.', levelId: 1 },
  { id: 194, name: 'Explora la cámara', description: 'Mueve la vista dentro del entorno con controles predeterminados.', levelId: 1 },
  { id: 195, name: 'Busca y reutiliza assets', description: 'Usa recursos gratuitos como modelos GLTF o texturas.', levelId: 1 },
  { id: 196, name: 'Agrega materiales y animaciones', description: 'Aplica texturas, efectos y movimientos simples.', levelId: 2 },
  { id: 197, name: 'Incluye interactividad básica', description: 'Detecta clics o colisiones para activar respuestas visuales.', levelId: 2 },
  { id: 198, name: 'Organiza escenas con jerarquías', description: 'Usa grupos y estructuras para gestionar objetos.', levelId: 2 },
  { id: 199, name: 'Integra componentes externos', description: 'Añade librerías o extensiones como controladores o UI.', levelId: 2 },
  { id: 200, name: 'Implementa lógica de navegación', description: 'Crea cambios de escena o menús interactivos.', levelId: 3 },
  { id: 201, name: 'Optimiza rendimiento', description: 'Reduce polígonos, ajusta iluminación y comprime texturas.', levelId: 3 },
  { id: 202, name: 'Configura escenas complejas', description: 'Controla cámaras dinámicas, múltiples luces y efectos.', levelId: 3 },
  { id: 203, name: 'Accede a una experiencia en VR', description: 'Usa gafas o simulador para explorar un entorno inmersivo.', levelId: 1 },
  { id: 204, name: 'Configura controles de vista', description: 'Ajusta la cámara para ver el entorno.', levelId: 1 },
  { id: 205, name: 'Agrega elementos interactivos básicos', description: 'Detecta interacciones por mirada o clic.', levelId: 1 },
  { id: 206, name: 'Comprende las zonas seguras', description: 'Diseña pensando en el confort visual y movimiento limitado.', levelId: 1 },
  { id: 207, name: 'Integra controladores VR', description: 'Usa manos virtuales o mandos para manipular objetos.', levelId: 2 },
  { id: 208, name: 'Aplica principios de accesibilidad en VR', description: 'Diseña elementos grandes, legibles y accesibles.', levelId: 2 },
  { id: 209, name: 'Implementa sonidos espaciales', description: 'Usa audio 3D para reforzar la inmersión.', levelId: 2 },
  { id: 210, name: 'Crea interacciones físicas', description: 'Detecta colisiones, movimientos y agarre de objetos.', levelId: 2 },
  { id: 211, name: 'Sincroniza múltiples usuarios', description: 'Configura experiencias colaborativas (multiplayer).', levelId: 3 },
  { id: 212, name: 'Desarrolla interfaces dentro del entorno', description: 'Menús 2D y 3D.', levelId: 3 },
  { id: 213, name: 'Ajusta el rendimiento para Oculus', description: 'Optimiza FPS, carga de assets y uso de shaders.', levelId: 3 },
  { id: 214, name: 'Proyecta modelos 3D sobre marcadores', description: 'Usa imágenes como disparadores para mostrar objetos.', levelId: 1 },
  { id: 215, name: 'Configura la cámara del dispositivo', description: 'Permite acceso al entorno físico a través del navegador.', levelId: 1 },
  { id: 216, name: 'Explora experiencias con AR en móvil', description: 'Visualiza modelos sencillos en contexto real.', levelId: 1 },
  { id: 217, name: 'Carga modelos 3D simples', description: 'Usa formatos compatibles como GLTF o OBJ.', levelId: 1 },
  { id: 218, name: 'Diseña interacciones sobre AR', description: 'Añade botones, animaciones o sonidos activados por el usuario.', levelId: 2 },
  { id: 219, name: 'Integra detección de superficie o imagen', description: 'Usa marcadores o planos reales para colocar contenido.', levelId: 2 },
  { id: 220, name: 'Adapta el diseño al contexto real', description: 'Considera iluminación, perspectiva y estabilidad de la imagen.', levelId: 2 },
  { id: 221, name: 'Controla el posicionamiento de objetos', description: 'Usa ejes y anclajes para fijar los modelos al entorno.', levelId: 2 },
  { id: 222, name: 'Combina geolocalización con AR', description: 'Muestra información según la posición GPS.', levelId: 3 },
  { id: 223, name: 'Configura experiencias sin marcador', description: 'Usa planos y reconocimiento espacial.', levelId: 3 },
  { id: 224, name: 'Mejora la estabilidad del rastreo', description: 'Ajusta sensibilidad y reduce errores de tracking.', levelId: 3 },
  { id: 279, name: 'Crea y ejecuta pruebas unitarias para componentes de interfaz', description: 'Verifica el comportamiento de componentes de forma aislada.', levelId: 1 },
  { id: 1001, name: 'Realiza limpieza básica de datos', description: 'Corrige o elimina registros incompletos, duplicados o inválidos.', levelId: 1 },
  { id: 1002, name: 'Representa datos mediante gráficas descriptivas', description: 'Utiliza visualizaciones simples para interpretar tendencias o relaciones.', levelId: 1 },
  { id: 1003, name: 'Ejecuta análisis exploratorio de datos (EDA)', description: 'Aplica técnicas estadísticas para entender la distribución, correlaciones y estructura de los datos.', levelId: 2 },
  { id: 1004, name: 'Automatiza tareas de limpieza y transformación', description: 'Construye flujos o scripts que aplican preprocesamiento de forma consistente y repetible.', levelId: 2 },
  { id: 1005, name: 'Aplica ingeniería de características y/o reducción de dimensionalidad', description: 'Simplifica la estructura de los datos preservando la información clave.', levelId: 3 },
  { id: 1006, name: 'Crea narrativas visuales basadas en datos', description: 'Presenta hallazgos mediante visualización clara y contextualizada para apoyar decisiones.', levelId: 3 },
  { id: 1011, name: 'Identifica el tipo de problema en función del objetivo y la naturaleza del dato', description: 'Diferencia entre tareas de clasificación, regresión, clustering, reducción de dimensionalidad y detección de anomalías.', levelId: 1 },
  { id: 1012, name: 'Divide el conjunto de datos en entrenamiento y prueba', description: 'Separa correctamente los datos para evaluar el rendimiento de los modelos.', levelId: 1 },
  { id: 1013, name: 'Selecciona y aplica algoritmos supervisados y no supervisados', description: 'Implementa modelos apropiados según el contexto.', levelId: 2 },
  { id: 1014, name: 'Evalúa el rendimiento del modelo con métricas apropiadas', description: 'Utiliza medidas como precisión, recall o error cuadrático medio para valorar resultados.', levelId: 2 },
  { id: 1015, name: 'Implementa validación cruzada y técnicas de ensemble', description: 'Aumenta la robustez del modelo mediante técnicas de validación y combinación de modelos.', levelId: 3 },
  { id: 1016, name: 'Aplica principios éticos y críticos en el uso de IA', description: 'Reflexiona sobre el impacto, el sesgo y la transparencia en los modelos desarrollados.', levelId: 3 },
  { id: 1380, name: 'Ajusta prompts y evalúa resultados de LLMs', description: 'Implementa flujos de prompt engineering y evalúa la relevancia, coherencia y seguridad de las respuestas generadas.', levelId: 3 },
  { id: 1381, name: 'Implementa modelos secuenciales (RNN, LSTM) para PLN', description: 'Desarrolla y aplica modelos de redes neuronales recurrentes para tareas de PLN.', levelId: 3 },
  { id: 1382, name: 'Implementa soluciones con LLMs y agentes', description: 'Desarrolla aplicaciones que integran modelos de lenguaje de gran tamaño y agentes para resolver tareas complejas.', levelId: 3 },
  { id: 2229, name: 'Diseña y ejecuta pruebas unitarias básicas', description: 'Implementa pruebas sobre funciones o componentes individuales para verificar su comportamiento esperado.', levelId: 1 },
  { id: 2230, name: 'Comprende los distintos tipos de pruebas', description: 'Distingue entre pruebas unitarias, de integración, funcionales y otras.', levelId: 1 },
  { id: 3000, name: 'Organización y legibilidad básica', description: 'Organiza el código con funciones claras, nombres descriptivos y estructuras limpias.', levelId: 1 },
  { id: 3002, name: 'Principios básicos (DRY, KISS, YAGNI)', description: 'Evita duplicación, mantiene la simplicidad y no implementa funcionalidades innecesarias.', levelId: 2 },
  { id: 3003, name: 'Declara y utiliza variables y tipos de datos', description: 'Define y usa variables y tipos de datos en el lenguaje de programación.', levelId: 1 },
  { id: 3004, name: 'Implementa estructuras de control de flujo', description: 'Utiliza condicionales y bucles para controlar la ejecución del programa.', levelId: 1 },
  { id: 3005, name: 'Utiliza colecciones y genéricos', description: 'Emplea listas, arrays, mapas y genéricos para gestionar conjuntos de datos.', levelId: 1 },
  { id: 3006, name: 'Paradigmas de programación', description: 'Reconoce, diferencia y aplica los principales paradigmas: imperativo, declarativo, OOP y funcional.', levelId: 2 },
  { id: 3007, name: 'Comprende y aplica conceptos básicos de concurrencia', description: 'Reconoce y utiliza mecanismos básicos de concurrencia y paralelismo.', levelId: 2 },
  { id: 3008, name: 'Principios SOLID', description: 'Aplica los principios de SOLID para mejorar la calidad del software.', levelId: 2 },
  { id: 3009, name: 'Patrones de diseño', description: 'Utiliza patrones comunes como Singleton, Factory, Observer, Strategy, Adapter, Decorator y otros.', levelId: 2 },
  { id: 3010, name: 'Patrones de arquitectura', description: 'Aplica patrones de arquitectura avanzados como MVC, MVVM, Microservicios, Clean Architecture, Hexagonal, CQRS.', levelId: 3 },
  { id: 3011, name: 'Refactorización avanzada', description: 'Realiza refactorización avanzada y promueve la mejora continua del código.', levelId: 3 },
  { id: 3013, name: 'Diseña sistemas sostenibles y escalables', description: 'Toma decisiones estructurales considerando mantenibilidad, escalabilidad y claridad.', levelId: 3 },
  { id: 9001, name: 'Aplica las Heurísticas de Nielsen', description: 'Evalúa y mejora la usabilidad de interfaces aplicando las 10 heurísticas de Nielsen para detectar problemas comunes de interacción.', levelId: 2 },
  { id: 9002, name: 'Utiliza principios de la Gestalt en el diseño', description: 'Organiza y agrupa elementos visuales aplicando principios de la Gestalt para mejorar la comprensión y experiencia del usuario.', levelId: 1 },
  { id: 9003, name: 'Optimiza el rendimiento de interfaces dinámicas', description: 'Identifica y aplica estrategias para mejorar la velocidad de renderizado, la eficiencia en el manejo de eventos y la carga de datos en aplicaciones con interfaces dinámicas.', levelId: 3 },
];

const tools = [
  { id: 1, name: 'Docker', description: 'Contenedorización de aplicaciones' },
  { id: 2, name: 'HTML', description: 'Estructura de páginas web' },
  { id: 3, name: 'CSS', description: 'Estilos de páginas web' },
  { id: 4, name: 'Git', description: 'Control de versiones' },
  { id: 5, name: 'GitHub', description: 'Plataforma de control de versiones' },
  { id: 6, name: 'JavaScript', description: 'Lenguaje de programación' },
  { id: 7, name: 'TypeScript', description: 'Lenguaje de programación' },
  { id: 8, name: 'React', description: 'Librería de JavaScript' },
  { id: 9, name: 'Next', description: 'Framework de React' },
  { id: 10, name: 'Tailwind CSS', description: 'Framework de CSS' },
  { id: 11, name: 'Node', description: 'Runtime de JavaScript' },
  { id: 12, name: 'Express', description: 'Framework de Node.js' },
  { id: 13, name: 'MongoDB', description: 'Base de datos NoSQL' },
  { id: 14, name: 'PostgreSQL', description: 'Base de datos relacional' },
  { id: 15, name: 'MySQL', description: 'Base de datos relacional' },
  { id: 16, name: 'IDE', description: 'Editor de código fuente' },
  { id: 17, name: 'Terminal (CLI)', description: 'Interfaz de línea de comandos para el sistema operativo' },
  { id: 18, name: 'Bootstrap', description: 'Framework para diseño responsive' },
  { id: 19, name: 'Jest', description: 'Framework de testing para JavaScript' },
  { id: 20, name: 'Figma', description: 'Herramienta de diseño de interfaces y prototipado' },
  { id: 21, name: 'draw.io', description: 'Herramienta para crear diagramas y flujos de trabajo' },
  { id: 22, name: 'Inspector de elementos', description: 'Herramienta de desarrollo para depurar y analizar páginas web' },
  { id: 23, name: 'Preprocesadores CSS (Sass/Less)', description: 'Sintaxis avanzada para escribir CSS de forma más eficiente' },
  { id: 24, name: 'Postman', description: 'Plataforma para construir y probar APIs' },
  { id: 25, name: 'API Rest', description: 'Arquitectura de software para crear servicios web' },
  { id: 26, name: 'Cypress', description: 'Framework de testing end-to-end para aplicaciones web' },
  { id: 27, name: 'ORM', description: 'Mapeo de datos objeto-relacional para interactuar con bases de datos' },
  { id: 28, name: 'RabbitMQ', description: 'Broker de mensajería para sistemas distribuidos' },
  { id: 29, name: 'Python', description: 'Lenguaje de programación de propósito general' },
  { id: 30, name: 'Django', description: 'Framework de desarrollo web de alto nivel para Python' },
  { id: 31, name: 'Scrum', description: 'Marco de trabajo para la gestión y desarrollo de proyectos ágiles' },
  { id: 32, name: 'Kanban', description: 'Método para gestionar el trabajo y mejorar el flujo de producción' },
  { id: 33, name: 'Jupyter', description: 'Entorno de computación interactiva para ciencia de datos y IA' },
  { id: 34, name: 'Selenium', description: 'Framework para la automatización de navegadores web' },
  { id: 35, name: 'Cronjobs', description: 'Programador de tareas basado en tiempo en sistemas Unix' },
  { id: 36, name: 'Diagrama de base de datos', description: 'Representación visual de la estructura de una base de datos' },
  { id: 37, name: 'Bases de datos vectoriales', description: 'Bases de datos optimizadas para almacenar y consultar embeddings vectoriales' },
  { id: 38, name: 'Pytest', description: 'Framework de testing para Python' },
  { id: 39, name: 'Unittest', description: 'Framework de testing para Python' },
  { id: 40, name: 'Render', description: 'Plataforma cloud para desplegar aplicaciones y sitios web' },
  { id: 41, name: 'Kubernetes', description: 'Plataforma de orquestación de contenedores' },
  { id: 42, name: 'Seaborn', description: 'Librería de visualización de datos para Python' },
  { id: 43, name: 'Matplotlib', description: 'Librería de visualización de datos para Python' },
  { id: 44, name: 'Plotly', description: 'Librería de visualización de datos para Python' },
  { id: 45, name: 'Dash', description: 'Framework para construir aplicaciones web analíticas con Python' },
  { id: 46, name: 'Streamlit', description: 'Framework para crear y compartir aplicaciones de datos' },
  { id: 47, name: 'Gradio', description: 'Librería para crear demos de machine learning con interfaces amigables' },
  { id: 48, name: 'PCA', description: 'Análisis de Componentes Principales para reducción de dimensionalidad' },
  { id: 49, name: 't-SNE', description: 'Visualización de datos de alta dimensionalidad' },
  { id: 50, name: 'Scikit-learn', description: 'Librería de machine learning para Python' },
  { id: 51, name: 'TensorFlow', description: 'Plataforma de código abierto para machine learning' },
  { id: 52, name: 'SVM', description: 'Máquinas de Vectores de Soporte para clasificación y regresión' },
  { id: 53, name: 'Logistic Regression', description: 'Modelo estadístico para clasificación binaria' },
  { id: 54, name: 'Linear Regression', description: 'Modelo estadístico para predecir valores continuos' },
  { id: 55, name: 'Decision Tree', description: 'Modelo de predicción basado en reglas de decisión' },
  { id: 56, name: 'Naive Bayes', description: 'Clasificador probabilístico basado en el teorema de Bayes' },
  { id: 57, name: 'Random Forest', description: 'Algoritmo de ensamblado para clasificación y regresión' },
  { id: 58, name: 'Gradient Boosting', description: 'Algoritmo de ensamblado para clasificación y regresión' },
  { id: 59, name: 'AdaBoost', description: 'Algoritmo de ensamblado para clasificación y regresión' },
  { id: 60, name: 'XGBoost', description: 'Implementación optimizada de gradient boosting' },
  { id: 61, name: 'LightGBM', description: 'Framework de gradient boosting rápido y eficiente' },
  { id: 62, name: 'MSE', description: 'Métrica de error cuadrático medio para regresión' },
  { id: 63, name: 'Recall', description: 'Métrica de evaluación para clasificación (sensibilidad)' },
  { id: 64, name: 'F1-Score', description: 'Métrica que combina precisión y recall para clasificación' },
  { id: 66, name: 'Algoritmo de Backpropagation', description: 'Algoritmo para entrenar redes neuronales artificiales' },
  { id: 67, name: 'Descenso del Gradiente', description: 'Algoritmo de optimización para encontrar mínimos de una función' },
  { id: 68, name: 'MLOPS', description: 'Prácticas para el despliegue y mantenimiento de modelos de machine learning' },
  { id: 72, name: 'LangChain', description: 'Framework para desarrollar aplicaciones impulsadas por modelos de lenguaje' },
  { id: 73, name: 'CrewAI', description: 'Framework para orquestar agentes de IA' },
  { id: 74, name: 'RAG', description: 'Generación Aumentada por Recuperación, un patrón de arquitectura para LLMs' },
  { id: 76, name: 'PyTorch', description: 'Librería de machine learning de código abierto basada en Torch' },
  { id: 77, name: 'YOLO', description: 'You Only Look Once, un modelo de detección de objetos en tiempo real' },
  { id: 78, name: 'R-CNN', description: 'Redes Neuronales Convolucionales basadas en Regiones para la detección de objetos' },
  { id: 79, name: 'SSD', description: 'Single Shot MultiBox Detector para la detección de objetos' },
  { id: 80, name: 'U-Net', description: 'Arquitectura de red neuronal para la segmentación de imágenes biomédicas' },
  { id: 81, name: 'SAM', description: 'Segment Anything Model, un modelo de segmentación de imágenes de Meta AI' },
  { id: 82, name: 'GANs', description: 'Redes Generativas Antagónicas para generar datos nuevos y sintéticos' },
  { id: 83, name: 'GitHub Actions', description: 'Plataforma de integración y despliegue continuo (CI/CD) de GitHub' },
  { id: 84, name: 'JWT', description: 'JSON Web Token' },
  { id: 87, name: 'Programación Orientada a Objetos', description: 'Paradigma de programación basado en el concepto de objetos' },
  { id: 88, name: 'Programación Funcional', description: 'Paradigma de programación basado en el uso de funciones' },
  { id: 89, name: 'SOLID', description: 'Principios de diseño de software' },
  { id: 90, name: 'A-Frame', description: 'Framework para crear experiencias de realidad virtual y aumentada en la web.' },
  { id: 91, name: 'Unity', description: 'Motor de desarrollo para crear experiencias 3D, VR y AR.' },
  { id: 92, name: 'Three', description: 'Librería JavaScript para gráficos 3D en la web.' },
  { id: 93, name: 'Babylon', description: 'Framework para crear gráficos 3D y experiencias VR/AR en la web.' },
  { id: 94, name: 'MindAR', description: 'Framework para realidad aumentada en la web, especialmente para móvil.' },
  { id: 95, name: 'Model Viewer', description: 'APIs de Google para realidad aumentada y procesamiento de imágenes.' },
  { id: 96, name: 'Blender', description: 'Software de modelado, animación y renderizado 3D de código abierto.' },
  { id: 97, name: 'Programación Imperativa', description: 'Paradigma de programación basado en instrucciones secuenciales' },
  { id: 98, name: 'Programación Declarativa', description: 'Paradigma de programación que expresa la lógica sin describir su control de flujo' },
  { id: 99, name: 'Patrones de diseño', description: 'Soluciones reutilizables a problemas comunes de diseño de software' },
  { id: 100, name: 'Patrones de arquitectura', description: 'Estructuras de alto nivel para organizar sistemas de software' },
  { id: 101, name: 'Clean Code', description: 'Principios y prácticas para escribir código limpio, legible y mantenible' },
  { id: 102, name: 'Refactoring', description: 'Técnicas para mejorar la estructura interna del código' },
  { id: 103, name: 'SQL', description: 'Lenguaje de consulta estructurado para gestión de bases de datos relacionales' },
  { id: 104, name: 'JUnit', description: 'Framework de testing para Java' },
  { id: 105, name: 'Mockito', description: 'Librería para mocking en tests de Java' },
  { id: 106, name: 'Spring', description: 'Framework de desarrollo de aplicaciones en Java' },
  { id: 107, name: 'Spring Boot', description: 'Herramienta para crear aplicaciones Spring de manera rápida y sencilla' },
  { id: 108, name: 'Spring Web', description: 'Módulo de Spring para el desarrollo de aplicaciones web y APIs REST' },
  { id: 109, name: 'Spring Security', description: 'Módulo de Spring para la gestión de autenticación y autorización' },
  { id: 110, name: 'JPA', description: 'Java Persistence API' },
  { id: 111, name: 'Basic Auth', description: 'Método de autenticación HTTP básico' },
  { id: 201, name: 'Polars', description: 'Librería de DataFrames para Python, alternativa a Pandas' },
  { id: 202, name: 'Scipy', description: 'Librería de computación científica para Python' },
  { id: 203, name: 'Statistics', description: 'Módulo de estadística en Python' },
  { id: 204, name: 'MLflow', description: 'Gestión del ciclo de vida de modelos de ML' },
  { id: 205, name: 'Optuna', description: 'Optimización de hiperparámetros para ML' },
  { id: 206, name: 'Numpy', description: 'Librería de álgebra lineal y operaciones numéricas para Python' },
  { id: 207, name: 'Pandas', description: 'Librería de manipulación y análisis de datos para Python' },
  { id: 208, name: 'Java', description: 'Lenguaje de programación orientado a objetos' },
  { id: 209, name: 'ESLint', description: 'Linter para JavaScript y TypeScript' },
  { id: 210, name: 'Pylint', description: 'Linter para Python' },
  { id: 211, name: 'Flake8', description: 'Linter para Python' },
  { id: 212, name: 'Prettier', description: 'Formatter para JavaScript, TypeScript y otros lenguajes' },
  { id: 213, name: 'Black', description: 'Formatter para Python' },
  { id: 214, name: 'SonarQube', description: 'Herramienta de análisis estático de código' },
  { id: 215, name: 'CodeClimate', description: 'Herramienta de análisis estático y calidad de código' },
  { id: 216, name: 'SonarLint', description: 'Extensión para análisis estático en el editor' },
  { id: 217, name: 'SpaCy', description: 'Librería de procesamiento de lenguaje natural en Python' },
  { id: 218, name: 'NLTK', description: 'Natural Language Toolkit, librería de PLN en Python' },
  { id: 219, name: 'Hugging Face Transformers', description: 'Librería para modelos preentrenados y LLMs' },
  { id: 220, name: 'Vitest', description: 'Framework de testing rápido y moderno para proyectos JavaScript y TypeScript' },
  { id: 221, name: 'GitHub Pages', description: 'Servicio de hosting estático para sitios web directamente desde repositorios de GitHub' },
  { id: 222, name: 'Netlify', description: 'Plataforma de despliegue y hosting para sitios web estáticos y JAMstack' },
  { id: 223, name: 'Vercel', description: 'Plataforma de despliegue y hosting optimizada para aplicaciones frontend y JAMstack' },
  { id: 224, name: 'Spring Framework', description: 'Framework principal para el desarrollo de aplicaciones empresariales en Java' },
  { id: 225, name: 'Spring Data', description: 'Proyecto de Spring para facilitar el acceso y persistencia de datos en Java' },
  { id: 226, name: 'Page Speed', description: 'Herramienta para analizar y optimizar el rendimiento de carga de páginas web' },
  { id: 227, name: 'Swagger', description: 'Herramienta para documentación, diseño y pruebas de APIs REST' },
  { id: 228, name: 'CORS', description: 'Mecanismo de seguridad que permite o restringe recursos solicitados desde otro dominio' },
  { id: 229, name: 'Beautiful Soup', description: 'Librería de Python para extraer información de archivos HTML y XML' },
  { id: 230, name: 'devcontainer', description: 'Entorno de desarrollo reproducible basado en contenedores para Visual Studio Code' },
  { id: 231, name: 'FastAPI', description: 'Framework moderno para construir APIs con Python, ideal para ML' },
  { id: 232, name: 'Apache Spark', description: 'Motor de procesamiento de datos distribuido' },
  { id: 233, name: 'Apache Kafka', description: 'Plataforma de streaming de eventos distribuida' },
];

const resources = [
  { id: 1, label: 'Repositorio sobre Docker', url: 'https://github.com/Factoria-F5-dev/docker', comments: 'Repositorio con explicación de Docker y ejemplos con node y Python' },
  { id: 2, label: 'Presentación de HTML', url: 'https://www.canva.com/design/DAF0Ww_M1eA/IhhlmVhp0MqHv7eXh-8EJA/view', comments: 'Presentación visual sobre los conceptos básicos de HTML.' },
  { id: 3, label: 'Presentación de CSS', url: 'https://www.canva.com/design/DAF0m6qsXCQ/F_bgscpvL22YjboR23JCEA/view', comments: 'Presentación visual sobre conceptos clave de CSS.' },
  { id: 4, label: 'Juego de Git', url: 'https://learngitbranching.js.org/?locale=es_ES', comments: 'Juego interactivo para aprender Git.' },
  { id: 5, label: 'GitHub Skills', url: 'https://skills.github.com/', comments: 'Web de formación oficial de GitHub.' },
  { id: 6, label: 'Web Instalación de MongoDB', url: 'https://alex-codingworld.notion.site/MongoDB-Installation-17799307f48b4b05967ab831dc9c97c7', comments: 'Web de cómo instalar paso a paso MongoDB.' },
  { id: 7, label: 'Repositorio sobre CRUD con Django', url: 'https://github.com/Factoria-F5-madrid/CRUD-django/tree/main', comments: 'Repositorio introducción a CRUD con Django' },
  { id: 8, label: 'Katas Js', url: 'https://github.com/Factoria-F5-madrid/katas-intro-js', comments: 'Repositorio con katas de introducción a JavaScript.' },
  { id: 9, label: '3blue1brown - Canal Matematicas', url: 'https://www.youtube.com/c/3blue1brown', comments: 'Canal de YouTube con explicaciones visuales de matemáticas.' },
];

const referents = [
  { id: 1, name: 'Celia Millán', avatar: 'https://avatars.githubusercontent.com/celiaMi?size=128', link: 'https://www.linkedin.com/in/celia-mill%C3%A1n-15465184/' },
  { id: 2, name: 'Ana Aragón', avatar: 'https://avatars.githubusercontent.com/anaaragon88?size=128', link: 'https://www.linkedin.com/in/anaaragonvazquez/' },
  { id: 3, name: 'Alexandra Zambrano', avatar: 'https://avatars.githubusercontent.com/AlexandraZambrano?size=128', link: 'https://www.linkedin.com/in/alexandra-zambrano-614309285/' },
  { id: 4, name: 'Jorge Bénitez', avatar: 'https://avatars.githubusercontent.com/signados?size=128', link: 'https://www.linkedin.com/in/jorgebenitezlopez/' },
  { id: 5, name: 'Paloma García', avatar: 'https://avatars.githubusercontent.com/palomaggc?size=128', link: 'https://www.linkedin.com/in/paloma-garcia-data-science/' },
  { id: 6, name: 'David Robert Núñez', avatar: 'https://avatars.githubusercontent.com/Mrrobert91?size=128', link: 'https://www.linkedin.com/in/david-robert/' },
];

const areas = [
  { id: 1, name: 'web', icon: 'icon-web', description: 'Desarrollo de aplicaciones y sitios web modernos, interactivos y accesibles.' },
  { id: 2, name: 'ai', icon: 'icon-ai', description: 'Inteligencia artificial para crear soluciones inteligentes.' },
  { id: 3, name: 'accessibility', icon: 'icon-accessibility', description: 'Accesibilidad web para personas con discapacidades.' },
  { id: 4, name: 'green', icon: 'icon-green', description: 'Habilidades digitales sostenibles y ecológicas.' },
  { id: 5, name: 'inmersivo', icon: 'icon-inmersivo', description: 'Desarrollo de aplicaciones inmersivas y realidades aumentadas.' },
];

const resourceTypes = [
  { id: 1, name: 'Repositorio' },
  { id: 2, name: 'Certificación' },
  { id: 3, name: 'Presentación' },
  { id: 4, name: 'Canva' },
  { id: 5, name: 'Juego' },
  { id: 6, name: 'Web' },
  { id: 7, name: 'Canal' },
];

// ─── RELACIONES ───────────────────────────────────────────────────────────────

const competenceIndicators = [
  { id: 1, id_competence: 1, id_indicator: 1 }, { id: 2, id_competence: 1, id_indicator: 2 },
  { id: 3, id_competence: 1, id_indicator: 3 }, { id: 4, id_competence: 1, id_indicator: 4 },
  { id: 5, id_competence: 1, id_indicator: 5 }, { id: 6, id_competence: 1, id_indicator: 6 },
  { id: 7, id_competence: 1, id_indicator: 7 }, { id: 8, id_competence: 1, id_indicator: 8 },
  { id: 9, id_competence: 1, id_indicator: 9 }, { id: 10, id_competence: 1, id_indicator: 10 },
  { id: 11, id_competence: 2, id_indicator: 11 }, { id: 12, id_competence: 2, id_indicator: 12 },
  { id: 13, id_competence: 2, id_indicator: 13 }, { id: 14, id_competence: 2, id_indicator: 14 },
  { id: 15, id_competence: 2, id_indicator: 15 }, { id: 16, id_competence: 2, id_indicator: 16 },
  { id: 17, id_competence: 2, id_indicator: 17 }, { id: 18, id_competence: 2, id_indicator: 18 },
  { id: 19, id_competence: 2, id_indicator: 19 },
  { id: 20, id_competence: 3, id_indicator: 20 }, { id: 21, id_competence: 3, id_indicator: 21 },
  { id: 22, id_competence: 3, id_indicator: 22 }, { id: 23, id_competence: 3, id_indicator: 23 },
  { id: 24, id_competence: 3, id_indicator: 24 }, { id: 25, id_competence: 3, id_indicator: 25 },
  { id: 26, id_competence: 3, id_indicator: 26 }, { id: 27, id_competence: 3, id_indicator: 27 },
  { id: 28, id_competence: 3, id_indicator: 28 }, { id: 29, id_competence: 3, id_indicator: 29 },
  { id: 30, id_competence: 3, id_indicator: 30 },
  { id: 414, id_competence: 4, id_indicator: 2229 }, { id: 415, id_competence: 4, id_indicator: 2230 },
  { id: 31, id_competence: 4, id_indicator: 31 }, { id: 32, id_competence: 4, id_indicator: 32 },
  { id: 33, id_competence: 4, id_indicator: 33 }, { id: 34, id_competence: 4, id_indicator: 34 },
  { id: 35, id_competence: 4, id_indicator: 35 }, { id: 36, id_competence: 4, id_indicator: 36 },
  { id: 37, id_competence: 4, id_indicator: 37 },
  { id: 38, id_competence: 5, id_indicator: 38 }, { id: 39, id_competence: 5, id_indicator: 39 },
  { id: 40, id_competence: 5, id_indicator: 40 }, { id: 41, id_competence: 5, id_indicator: 41 },
  { id: 42, id_competence: 5, id_indicator: 42 }, { id: 43, id_competence: 5, id_indicator: 43 },
  { id: 44, id_competence: 5, id_indicator: 44 }, { id: 45, id_competence: 5, id_indicator: 45 },
  { id: 46, id_competence: 5, id_indicator: 46 },
  { id: 48, id_competence: 6, id_indicator: 48 }, { id: 49, id_competence: 6, id_indicator: 49 },
  { id: 50, id_competence: 6, id_indicator: 50 }, { id: 51, id_competence: 6, id_indicator: 51 },
  { id: 52, id_competence: 6, id_indicator: 52 }, { id: 53, id_competence: 6, id_indicator: 53 },
  { id: 54, id_competence: 6, id_indicator: 54 }, { id: 55, id_competence: 6, id_indicator: 55 },
  { id: 56, id_competence: 6, id_indicator: 56 }, { id: 57, id_competence: 6, id_indicator: 57 },
  { id: 58, id_competence: 6, id_indicator: 58 }, { id: 100, id_competence: 6, id_indicator: 101 },
  { id: 69, id_competence: 7, id_indicator: 69 }, { id: 70, id_competence: 7, id_indicator: 70 },
  { id: 71, id_competence: 7, id_indicator: 71 }, { id: 72, id_competence: 7, id_indicator: 72 },
  { id: 73, id_competence: 7, id_indicator: 73 }, { id: 74, id_competence: 7, id_indicator: 74 },
  { id: 75, id_competence: 7, id_indicator: 75 }, { id: 76, id_competence: 7, id_indicator: 76 },
  { id: 78, id_competence: 7, id_indicator: 78 }, { id: 9003, id_competence: 7, id_indicator: 9003 },
  { id: 4001, id_competence: 8, id_indicator: 3000 }, { id: 4002, id_competence: 8, id_indicator: 3002 },
  { id: 4003, id_competence: 8, id_indicator: 3003 }, { id: 4004, id_competence: 8, id_indicator: 3004 },
  { id: 4005, id_competence: 8, id_indicator: 3005 }, { id: 4006, id_competence: 8, id_indicator: 3006 },
  { id: 4007, id_competence: 8, id_indicator: 3007 }, { id: 4008, id_competence: 8, id_indicator: 3008 },
  { id: 4009, id_competence: 8, id_indicator: 3009 }, { id: 4010, id_competence: 8, id_indicator: 3010 },
  { id: 4011, id_competence: 8, id_indicator: 3011 }, { id: 4013, id_competence: 8, id_indicator: 3013 },
  { id: 59, id_competence: 9, id_indicator: 59 }, { id: 60, id_competence: 9, id_indicator: 60 },
  { id: 61, id_competence: 9, id_indicator: 61 }, { id: 62, id_competence: 9, id_indicator: 62 },
  { id: 63, id_competence: 9, id_indicator: 63 }, { id: 64, id_competence: 9, id_indicator: 64 },
  { id: 65, id_competence: 9, id_indicator: 65 }, { id: 66, id_competence: 9, id_indicator: 66 },
  { id: 67, id_competence: 9, id_indicator: 67 }, { id: 68, id_competence: 9, id_indicator: 68 },
  { id: 9002, id_competence: 9, id_indicator: 9002 }, { id: 9004, id_competence: 9, id_indicator: 79 },
  { id: 90, id_competence: 10, id_indicator: 90 }, { id: 91, id_competence: 10, id_indicator: 91 },
  { id: 92, id_competence: 10, id_indicator: 92 }, { id: 93, id_competence: 10, id_indicator: 93 },
  { id: 94, id_competence: 10, id_indicator: 94 }, { id: 95, id_competence: 10, id_indicator: 95 },
  { id: 97, id_competence: 10, id_indicator: 97 }, { id: 98, id_competence: 10, id_indicator: 98 },
  { id: 99, id_competence: 10, id_indicator: 99 },
  { id: 102, id_competence: 12, id_indicator: 102 }, { id: 103, id_competence: 12, id_indicator: 103 },
  { id: 104, id_competence: 12, id_indicator: 104 }, { id: 105, id_competence: 12, id_indicator: 105 },
  { id: 106, id_competence: 12, id_indicator: 106 }, { id: 107, id_competence: 12, id_indicator: 107 },
  { id: 2001, id_competence: 13, id_indicator: 1001 }, { id: 2002, id_competence: 13, id_indicator: 1002 },
  { id: 2003, id_competence: 13, id_indicator: 1003 }, { id: 2004, id_competence: 13, id_indicator: 1004 },
  { id: 2005, id_competence: 13, id_indicator: 1005 }, { id: 2006, id_competence: 13, id_indicator: 1006 },
  { id: 2011, id_competence: 14, id_indicator: 1011 }, { id: 2012, id_competence: 14, id_indicator: 1012 },
  { id: 2013, id_competence: 14, id_indicator: 1013 }, { id: 2014, id_competence: 14, id_indicator: 1014 },
  { id: 2015, id_competence: 14, id_indicator: 1015 }, { id: 2016, id_competence: 14, id_indicator: 1016 },
  { id: 120, id_competence: 15, id_indicator: 120 }, { id: 121, id_competence: 15, id_indicator: 121 },
  { id: 122, id_competence: 15, id_indicator: 122 }, { id: 123, id_competence: 15, id_indicator: 123 },
  { id: 124, id_competence: 15, id_indicator: 124 }, { id: 125, id_competence: 15, id_indicator: 125 },
  { id: 126, id_competence: 15, id_indicator: 126 }, { id: 127, id_competence: 15, id_indicator: 127 },
  { id: 128, id_competence: 15, id_indicator: 128 },
  { id: 129, id_competence: 16, id_indicator: 129 }, { id: 130, id_competence: 16, id_indicator: 130 },
  { id: 131, id_competence: 16, id_indicator: 131 }, { id: 132, id_competence: 16, id_indicator: 132 },
  { id: 133, id_competence: 16, id_indicator: 133 }, { id: 134, id_competence: 16, id_indicator: 134 },
  { id: 135, id_competence: 16, id_indicator: 135 }, { id: 9130, id_competence: 16, id_indicator: 1380 },
  { id: 9135, id_competence: 16, id_indicator: 1381 }, { id: 9136, id_competence: 16, id_indicator: 1382 },
  { id: 138, id_competence: 17, id_indicator: 138 }, { id: 139, id_competence: 17, id_indicator: 139 },
  { id: 141, id_competence: 17, id_indicator: 141 }, { id: 142, id_competence: 17, id_indicator: 142 },
  { id: 144, id_competence: 17, id_indicator: 144 }, { id: 145, id_competence: 17, id_indicator: 145 },
  { id: 146, id_competence: 17, id_indicator: 146 },
  { id: 147, id_competence: 18, id_indicator: 192 }, { id: 148, id_competence: 18, id_indicator: 193 },
  { id: 149, id_competence: 18, id_indicator: 194 }, { id: 150, id_competence: 18, id_indicator: 195 },
  { id: 151, id_competence: 18, id_indicator: 196 }, { id: 152, id_competence: 18, id_indicator: 197 },
  { id: 153, id_competence: 18, id_indicator: 198 }, { id: 154, id_competence: 18, id_indicator: 199 },
  { id: 155, id_competence: 18, id_indicator: 200 }, { id: 156, id_competence: 18, id_indicator: 201 },
  { id: 157, id_competence: 18, id_indicator: 202 },
  { id: 158, id_competence: 19, id_indicator: 203 }, { id: 159, id_competence: 19, id_indicator: 204 },
  { id: 160, id_competence: 19, id_indicator: 205 }, { id: 161, id_competence: 19, id_indicator: 206 },
  { id: 162, id_competence: 19, id_indicator: 207 }, { id: 163, id_competence: 19, id_indicator: 208 },
  { id: 164, id_competence: 19, id_indicator: 209 }, { id: 165, id_competence: 19, id_indicator: 210 },
  { id: 166, id_competence: 19, id_indicator: 211 }, { id: 167, id_competence: 19, id_indicator: 212 },
  { id: 168, id_competence: 19, id_indicator: 213 },
  { id: 169, id_competence: 20, id_indicator: 214 }, { id: 170, id_competence: 20, id_indicator: 215 },
  { id: 171, id_competence: 20, id_indicator: 216 }, { id: 172, id_competence: 20, id_indicator: 217 },
  { id: 173, id_competence: 20, id_indicator: 218 }, { id: 174, id_competence: 20, id_indicator: 219 },
  { id: 175, id_competence: 20, id_indicator: 220 }, { id: 176, id_competence: 20, id_indicator: 221 },
  { id: 177, id_competence: 20, id_indicator: 222 }, { id: 178, id_competence: 20, id_indicator: 223 },
  { id: 179, id_competence: 20, id_indicator: 224 },
];

const competenceTools = [
  { id: 1, id_competence: 1, id_tool: 1 }, { id: 2, id_competence: 1, id_tool: 4 },
  { id: 3, id_competence: 1, id_tool: 5 }, { id: 4, id_competence: 1, id_tool: 16 },
  { id: 5, id_competence: 1, id_tool: 17 }, { id: 3013, id_competence: 1, id_tool: 230 },
  { id: 6, id_competence: 2, id_tool: 5 }, { id: 7, id_competence: 2, id_tool: 31 },
  { id: 8, id_competence: 2, id_tool: 32 },
  { id: 9, id_competence: 3, id_tool: 13 }, { id: 10, id_competence: 3, id_tool: 14 },
  { id: 11, id_competence: 3, id_tool: 27 }, { id: 12, id_competence: 3, id_tool: 36 },
  { id: 13, id_competence: 3, id_tool: 37 }, { id: 169, id_competence: 3, id_tool: 103 },
  { id: 18, id_competence: 4, id_tool: 19 }, { id: 22, id_competence: 4, id_tool: 26 },
  { id: 24, id_competence: 4, id_tool: 34 }, { id: 25, id_competence: 4, id_tool: 38 },
  { id: 26, id_competence: 4, id_tool: 39 }, { id: 170, id_competence: 4, id_tool: 104 },
  { id: 171, id_competence: 4, id_tool: 105 }, { id: 20, id_competence: 4, id_tool: 24 },
  { id: 172, id_competence: 4, id_tool: 22 }, { id: 180, id_competence: 4, id_tool: 220 },
  { id: 195, id_competence: 4, id_tool: 226 },
  { id: 27, id_competence: 5, id_tool: 1 }, { id: 28, id_competence: 5, id_tool: 4 },
  { id: 29, id_competence: 5, id_tool: 5 }, { id: 31, id_competence: 5, id_tool: 35 },
  { id: 32, id_competence: 5, id_tool: 40 }, { id: 33, id_competence: 5, id_tool: 41 },
  { id: 34, id_competence: 5, id_tool: 68 }, { id: 35, id_competence: 5, id_tool: 83 },
  { id: 181, id_competence: 5, id_tool: 221 }, { id: 182, id_competence: 5, id_tool: 222 },
  { id: 183, id_competence: 5, id_tool: 223 },
  { id: 36, id_competence: 6, id_tool: 11 }, { id: 37, id_competence: 6, id_tool: 12 },
  { id: 41, id_competence: 6, id_tool: 6 }, { id: 42, id_competence: 6, id_tool: 7 },
  { id: 43, id_competence: 6, id_tool: 24 }, { id: 45, id_competence: 6, id_tool: 27 },
  { id: 46, id_competence: 6, id_tool: 28 }, { id: 47, id_competence: 6, id_tool: 29 },
  { id: 48, id_competence: 6, id_tool: 30 }, { id: 49, id_competence: 6, id_tool: 84 },
  { id: 174, id_competence: 6, id_tool: 107 }, { id: 176, id_competence: 6, id_tool: 109 },
  { id: 179, id_competence: 6, id_tool: 208 }, { id: 184, id_competence: 6, id_tool: 224 },
  { id: 185, id_competence: 6, id_tool: 225 }, { id: 189, id_competence: 6, id_tool: 25 },
  { id: 190, id_competence: 6, id_tool: 227 }, { id: 191, id_competence: 6, id_tool: 228 },
  { id: 192, id_competence: 6, id_tool: 231 },
  { id: 50, id_competence: 7, id_tool: 2 }, { id: 51, id_competence: 7, id_tool: 3 },
  { id: 52, id_competence: 7, id_tool: 6 }, { id: 53, id_competence: 7, id_tool: 7 },
  { id: 54, id_competence: 7, id_tool: 8 }, { id: 55, id_competence: 7, id_tool: 9 },
  { id: 56, id_competence: 7, id_tool: 10 }, { id: 57, id_competence: 7, id_tool: 18 },
  { id: 58, id_competence: 7, id_tool: 22 }, { id: 59, id_competence: 7, id_tool: 23 },
  { id: 80, id_competence: 7, id_tool: 46 }, { id: 187, id_competence: 7, id_tool: 226 },
  { id: 72, id_competence: 8, id_tool: 209 }, { id: 73, id_competence: 8, id_tool: 210 },
  { id: 74, id_competence: 8, id_tool: 211 }, { id: 75, id_competence: 8, id_tool: 212 },
  { id: 76, id_competence: 8, id_tool: 213 }, { id: 77, id_competence: 8, id_tool: 214 },
  { id: 78, id_competence: 8, id_tool: 215 }, { id: 79, id_competence: 8, id_tool: 216 },
  { id: 186, id_competence: 8, id_tool: 226 }, { id: 193, id_competence: 8, id_tool: 227 },
  { id: 194, id_competence: 8, id_tool: 228 },
  { id: 64, id_competence: 9, id_tool: 2 }, { id: 65, id_competence: 9, id_tool: 3 },
  { id: 66, id_competence: 9, id_tool: 20 }, { id: 67, id_competence: 9, id_tool: 21 },
  { id: 68, id_competence: 10, id_tool: 2 }, { id: 69, id_competence: 10, id_tool: 3 },
  { id: 70, id_competence: 10, id_tool: 10 }, { id: 71, id_competence: 10, id_tool: 18 },
  { id: 721, id_competence: 10, id_tool: 20 }, { id: 73, id_competence: 10, id_tool: 22 },
  { id: 74, id_competence: 10, id_tool: 23 }, { id: 188, id_competence: 10, id_tool: 226 },
  { id: 200, id_competence: 12, id_tool: 229 }, { id: 77, id_competence: 12, id_tool: 34 },
  { id: 3000, id_competence: 13, id_tool: 29 }, { id: 3002, id_competence: 13, id_tool: 206 },
  { id: 3003, id_competence: 13, id_tool: 207 }, { id: 3004, id_competence: 13, id_tool: 201 },
  { id: 3005, id_competence: 13, id_tool: 43 }, { id: 3006, id_competence: 13, id_tool: 44 },
  { id: 3007, id_competence: 13, id_tool: 45 }, { id: 3008, id_competence: 13, id_tool: 46 },
  { id: 3009, id_competence: 13, id_tool: 47 }, { id: 3010, id_competence: 13, id_tool: 202 },
  { id: 3011, id_competence: 13, id_tool: 203 }, { id: 3012, id_competence: 13, id_tool: 50 },
  { id: 3021, id_competence: 14, id_tool: 29 }, { id: 3022, id_competence: 14, id_tool: 33 },
  { id: 3023, id_competence: 14, id_tool: 207 }, { id: 3024, id_competence: 14, id_tool: 206 },
  { id: 3025, id_competence: 14, id_tool: 43 }, { id: 3026, id_competence: 14, id_tool: 42 },
  { id: 3027, id_competence: 14, id_tool: 50 }, { id: 3028, id_competence: 14, id_tool: 204 },
  { id: 3029, id_competence: 14, id_tool: 205 },
  { id: 110, id_competence: 15, id_tool: 29 }, { id: 111, id_competence: 15, id_tool: 33 },
  { id: 112, id_competence: 15, id_tool: 50 }, { id: 113, id_competence: 15, id_tool: 51 },
  { id: 114, id_competence: 15, id_tool: 66 }, { id: 115, id_competence: 15, id_tool: 67 },
  { id: 116, id_competence: 15, id_tool: 76 },
  { id: 117, id_competence: 16, id_tool: 29 }, { id: 118, id_competence: 16, id_tool: 33 },
  { id: 119, id_competence: 16, id_tool: 50 }, { id: 120, id_competence: 16, id_tool: 51 },
  { id: 125, id_competence: 16, id_tool: 72 }, { id: 126, id_competence: 16, id_tool: 73 },
  { id: 127, id_competence: 16, id_tool: 74 }, { id: 129, id_competence: 16, id_tool: 217 },
  { id: 9132, id_competence: 16, id_tool: 218 }, { id: 9133, id_competence: 16, id_tool: 219 },
  { id: 9134, id_competence: 16, id_tool: 37 },
  { id: 130, id_competence: 17, id_tool: 29 }, { id: 131, id_competence: 17, id_tool: 33 },
  { id: 132, id_competence: 17, id_tool: 50 }, { id: 133, id_competence: 17, id_tool: 51 },
  { id: 135, id_competence: 17, id_tool: 76 }, { id: 136, id_competence: 17, id_tool: 77 },
  { id: 137, id_competence: 17, id_tool: 78 }, { id: 138, id_competence: 17, id_tool: 79 },
  { id: 139, id_competence: 17, id_tool: 80 }, { id: 140, id_competence: 17, id_tool: 81 },
  { id: 141, id_competence: 17, id_tool: 82 },
  { id: 158, id_competence: 18, id_tool: 90 }, { id: 159, id_competence: 18, id_tool: 91 },
  { id: 160, id_competence: 18, id_tool: 92 }, { id: 167, id_competence: 18, id_tool: 96 },
  { id: 161, id_competence: 19, id_tool: 90 }, { id: 162, id_competence: 19, id_tool: 91 },
  { id: 163, id_competence: 19, id_tool: 93 }, { id: 168, id_competence: 19, id_tool: 96 },
  { id: 164, id_competence: 20, id_tool: 90 }, { id: 165, id_competence: 20, id_tool: 94 },
  { id: 166, id_competence: 20, id_tool: 95 }, { id: 1691, id_competence: 20, id_tool: 96 },
];

const competenceResources = [
  { id: 1, id_competence: 14, id_resource: 9 },
  { id: 2, id_competence: 1, id_resource: 1 },
  { id: 3, id_competence: 1, id_resource: 4 },
  { id: 4, id_competence: 1, id_resource: 5 },
  { id: 5, id_competence: 10, id_resource: 2 },
  { id: 6, id_competence: 10, id_resource: 3 },
  { id: 7, id_competence: 8, id_resource: 8 },
  { id: 8, id_competence: 6, id_resource: 7 },
  { id: 9, id_competence: 3, id_resource: 6 },
];

const competenceAreas = [
  { id: 1, id_competence: 1, id_area: 1 }, { id: 2, id_competence: 1, id_area: 2 },
  { id: 3, id_competence: 2, id_area: 1 }, { id: 4, id_competence: 2, id_area: 2 },
  { id: 5, id_competence: 3, id_area: 1 }, { id: 6, id_competence: 3, id_area: 2 },
  { id: 7, id_competence: 4, id_area: 1 }, { id: 8, id_competence: 4, id_area: 2 },
  { id: 9, id_competence: 5, id_area: 1 }, { id: 10, id_competence: 5, id_area: 2 },
  { id: 11, id_competence: 6, id_area: 1 }, { id: 12, id_competence: 6, id_area: 2 },
  { id: 13, id_competence: 7, id_area: 1 }, { id: 14, id_competence: 7, id_area: 2 },
  { id: 15, id_competence: 8, id_area: 1 }, { id: 16, id_competence: 8, id_area: 2 },
  { id: 17, id_competence: 9, id_area: 1 }, { id: 18, id_competence: 10, id_area: 1 },
  { id: 19, id_competence: 11, id_area: 1 },
  { id: 20, id_competence: 12, id_area: 2 }, { id: 21, id_competence: 13, id_area: 2 },
  { id: 22, id_competence: 14, id_area: 2 }, { id: 23, id_competence: 15, id_area: 2 },
  { id: 24, id_competence: 16, id_area: 2 }, { id: 25, id_competence: 17, id_area: 2 },
  { id: 26, id_competence: 9, id_area: 3 }, { id: 27, id_competence: 10, id_area: 3 },
  { id: 28, id_competence: 3, id_area: 4 }, { id: 29, id_competence: 5, id_area: 4 },
  { id: 30, id_competence: 6, id_area: 4 }, { id: 31, id_competence: 7, id_area: 4 },
  { id: 32, id_competence: 8, id_area: 4 }, { id: 33, id_competence: 9, id_area: 4 },
  { id: 41, id_competence: 10, id_area: 4 },
  { id: 34, id_competence: 18, id_area: 5 }, { id: 35, id_competence: 19, id_area: 5 },
  { id: 36, id_competence: 20, id_area: 5 },
  { id: 38, id_competence: 18, id_area: 1 }, { id: 39, id_competence: 19, id_area: 1 },
  { id: 40, id_competence: 20, id_area: 1 },
];

const toolIndicators = [
  { id: 1, id_tool: 1, id_indicator: 147 }, { id: 2, id_tool: 1, id_indicator: 148 },
  { id: 3, id_tool: 1, id_indicator: 149 }, { id: 4, id_tool: 1, id_indicator: 150 },
  { id: 5, id_tool: 1, id_indicator: 151 }, { id: 6, id_tool: 1, id_indicator: 152 },
  { id: 7, id_tool: 1, id_indicator: 153 }, { id: 8, id_tool: 1, id_indicator: 154 },
  { id: 9, id_tool: 1, id_indicator: 155 },
  { id: 10, id_tool: 2, id_indicator: 156 }, { id: 11, id_tool: 2, id_indicator: 157 },
  { id: 12, id_tool: 2, id_indicator: 158 }, { id: 13, id_tool: 2, id_indicator: 159 },
  { id: 14, id_tool: 2, id_indicator: 160 }, { id: 15, id_tool: 2, id_indicator: 161 },
  { id: 16, id_tool: 2, id_indicator: 162 }, { id: 17, id_tool: 2, id_indicator: 163 },
  { id: 18, id_tool: 2, id_indicator: 164 },
  { id: 19, id_tool: 3, id_indicator: 165 }, { id: 20, id_tool: 3, id_indicator: 166 },
  { id: 21, id_tool: 3, id_indicator: 167 }, { id: 22, id_tool: 3, id_indicator: 168 },
  { id: 23, id_tool: 3, id_indicator: 169 }, { id: 24, id_tool: 3, id_indicator: 170 },
  { id: 25, id_tool: 3, id_indicator: 171 }, { id: 26, id_tool: 3, id_indicator: 172 },
  { id: 27, id_tool: 3, id_indicator: 173 },
  { id: 28, id_tool: 4, id_indicator: 174 }, { id: 29, id_tool: 4, id_indicator: 175 },
  { id: 30, id_tool: 4, id_indicator: 176 }, { id: 31, id_tool: 4, id_indicator: 177 },
  { id: 32, id_tool: 4, id_indicator: 178 }, { id: 33, id_tool: 4, id_indicator: 179 },
  { id: 34, id_tool: 4, id_indicator: 180 }, { id: 35, id_tool: 4, id_indicator: 181 },
  { id: 36, id_tool: 4, id_indicator: 182 },
  { id: 37, id_tool: 5, id_indicator: 183 }, { id: 38, id_tool: 5, id_indicator: 184 },
  { id: 39, id_tool: 5, id_indicator: 185 }, { id: 40, id_tool: 5, id_indicator: 186 },
  { id: 41, id_tool: 5, id_indicator: 187 }, { id: 42, id_tool: 5, id_indicator: 188 },
  { id: 43, id_tool: 5, id_indicator: 189 }, { id: 44, id_tool: 5, id_indicator: 190 },
  { id: 45, id_tool: 5, id_indicator: 191 },
];

const toolResources = [
  { id: 1, id_tool: 1, id_resource: 1 },
  { id: 2, id_tool: 2, id_resource: 2 },
  { id: 3, id_tool: 3, id_resource: 3 },
  { id: 4, id_tool: 4, id_resource: 4 },
  { id: 5, id_tool: 5, id_resource: 5 },
  { id: 6, id_tool: 6, id_resource: 8 },
  { id: 7, id_tool: 30, id_resource: 7 },
];

const toolReferents = [
  { id: 1, id_tool: 1, id_referent: 4 }, { id: 2, id_tool: 1, id_referent: 3 },
  { id: 3, id_tool: 2, id_referent: 1 }, { id: 4, id_tool: 2, id_referent: 2 },
  { id: 5, id_tool: 3, id_referent: 2 }, { id: 6, id_tool: 3, id_referent: 1 },
  { id: 7, id_tool: 4, id_referent: 3 }, { id: 8, id_tool: 4, id_referent: 4 },
  { id: 9, id_tool: 5, id_referent: 3 }, { id: 10, id_tool: 5, id_referent: 4 },
];

const resourceTypesRel = [
  { id: 1, id_resource: 1, id_type: 1 }, { id: 2, id_resource: 2, id_type: 4 },
  { id: 3, id_resource: 2, id_type: 3 }, { id: 4, id_resource: 3, id_type: 4 },
  { id: 5, id_resource: 3, id_type: 3 }, { id: 6, id_resource: 4, id_type: 5 },
  { id: 7, id_resource: 5, id_type: 6 }, { id: 8, id_resource: 6, id_type: 6 },
  { id: 9, id_resource: 7, id_type: 1 }, { id: 10, id_resource: 8, id_type: 1 },
  { id: 11, id_resource: 9, id_type: 7 },
];

const resourceReferents = [
  { id: 1, id_resource: 1, id_referent: 4 }, { id: 2, id_resource: 1, id_referent: 3 },
  { id: 3, id_resource: 2, id_referent: 1 }, { id: 4, id_resource: 2, id_referent: 2 },
  { id: 5, id_resource: 3, id_referent: 1 }, { id: 6, id_resource: 4, id_referent: 4 },
  { id: 7, id_resource: 5, id_referent: 4 }, { id: 8, id_resource: 6, id_referent: 3 },
  { id: 9, id_resource: 7, id_referent: 3 }, { id: 10, id_resource: 8, id_referent: 1 },
  { id: 11, id_resource: 9, id_referent: 6 },
];

// ─── MIGRACIÓN ────────────────────────────────────────────────────────────────

async function migrate() {
  const client = new MongoClient(MONGO_URI);

  try {
    await client.connect();
    console.log('✅ Conectado a MongoDB');

    const db = client.db(DB_NAME);

    const collections = [
      { name: 'levels', data: levels },
      { name: 'competences', data: competences },
      { name: 'indicators', data: indicators },
      { name: 'tools', data: tools },
      { name: 'resources', data: resources },
      { name: 'referents', data: referents },
      { name: 'areas', data: areas },
      { name: 'resourceTypes', data: resourceTypes },
      // Relaciones
      { name: 'competenceIndicators', data: competenceIndicators },
      { name: 'competenceTools', data: competenceTools },
      { name: 'competenceResources', data: competenceResources },
      { name: 'competenceAreas', data: competenceAreas },
      { name: 'toolIndicators', data: toolIndicators },
      { name: 'toolResources', data: toolResources },
      { name: 'toolReferents', data: toolReferents },
      { name: 'resourceTypesRel', data: resourceTypesRel },
      { name: 'resourceReferents', data: resourceReferents },
    ];

    for (const col of collections) {
      const existing = await db.collection(col.name).countDocuments();
      if (existing > 0) {
        console.log(`⚠️  Colección '${col.name}' ya tiene ${existing} documentos. Saltando...`);
        continue;
      }
      await db.collection(col.name).insertMany(col.data);
      console.log(`📦 Colección '${col.name}' creada con ${col.data.length} documentos.`);
    }

    // Crear índices útiles
    await db.collection('competenceIndicators').createIndex({ id_competence: 1 });
    await db.collection('competenceIndicators').createIndex({ id_indicator: 1 });
    await db.collection('competenceTools').createIndex({ id_competence: 1 });
    await db.collection('competenceTools').createIndex({ id_tool: 1 });
    await db.collection('competenceAreas').createIndex({ id_competence: 1 });
    await db.collection('competenceAreas').createIndex({ id_area: 1 });
    await db.collection('toolIndicators').createIndex({ id_tool: 1 });
    await db.collection('toolReferents').createIndex({ id_tool: 1 });
    await db.collection('toolResources').createIndex({ id_tool: 1 });
    await db.collection('resourceReferents').createIndex({ id_resource: 1 });
    await db.collection('indicators').createIndex({ levelId: 1 });

    console.log('\n✅ Migración completada con éxito.');
  } catch (err) {
    console.error('❌ Error durante la migración:', err);
    process.exit(1);
  } finally {
    await client.close();
  }
}

migrate();